services:
  frontend:
    build: ./frontend
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
    networks:
      - jhcapp

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - jhcapp

volumes:
  redis_data:

networks:
  jhcapp:
    driver: bridge
